name: Promote (light)
on:
  workflow_dispatch:
    inputs:
      model_version:
        description: "Specific version (optional)"
        required: false
        default: ""
  push:
    branches: ["master"]   # í ½í±ˆ ì¶”ê°€: masterì— í‘¸ì‹œë  ë•Œ 1íšŒ ìë™ ì‹¤í–‰

jobs:
  promote:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install mlflow==2.16.2
      - name: Promote in MLflow
        run: python promote_to_prod.py
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MODEL_NAME: light-logreg
          MODEL_VERSION: ${{ github.event.inputs.model_version }}
      - name: Smoke
        run: bash smoke.sh
        env:
          URL: http://light-serve.mlops.svc.cluster.local:8000

